In [2]:
import pandas as pd
data = {
 "calories": [420, 380, 390],
 "duration": [50, 40, 45]
}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
df.values

array([[420,  50],
       [380,  40],
       [390,  45]], dtype=int64)

In [11]:
df.columns

Index(['calories', 'duration'], dtype='object')

In [12]:
df["calories"]

0    420
1    380
2    390
Name: calories, dtype: int64

In [17]:
population_data = pd.Series({
      'California': 38332521,
      'Florida': 19552860,
      'Illinois': 12882135,
      'New York': 19651127,
      'Texas': 26448193
})
# Construct a DataFrame from the Series
df = pd.DataFrame(population_data, columns=['Population'])
# Display the DataFrame
print(df)


            Population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193


In [18]:
import pandas as pd
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(pd.DataFrame(data))


   a  b
0  0  0
1  1  2
2  2  4


In [19]:
data=[{'a':0,'b':0},{'a':1,'b':2},{'a':2,'b':4}]
print(pd.DataFrame(data))

   a  b
0  0  0
1  1  2
2  2  4


In [22]:
df=pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])
print(df)


     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0


In [28]:
# Population data
population = pd.Series({
    'California': 38332521,
    'Florida': 19552860,
    'Illinois': 12882135,
    'New York': 19651127,
    'Texas': 26448193
})
# Area data
area = pd.Series({
    'California': 423967,
    'Florida': 170312,
    'Illinois': 149995,
    'New York': 141297,
    'Texas': 695662
})


In [29]:
df=pd.DataFrame({"Population":population,"Area":area})
print(df)

            Population    Area
California    38332521  423967
Florida       19552860  170312
Illinois      12882135  149995
New York      19651127  141297
Texas         26448193  695662


In [31]:
df=pd.DataFrame(np.random.random((3, 2)),
columns=['foo', 'bar'],
index=['a', 'b', 'c'])
print(df)


        foo       bar
a  0.323362  0.521295
b  0.540120  0.087090
c  0.563046  0.795285


In [32]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
df=pd.DataFrame(A)
print(df)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0


In [33]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind)


Index([2, 3, 5, 7, 11], dtype='int64')


In [34]:
ind[3]

7

In [35]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [36]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [38]:
ind[1]=40

TypeError: Index does not support mutable operations

In [43]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
print(indA.intersection(indB)) # intersection

print(indA.union(indB)) # union

print(indA.symmetric_difference(indB)) # symmetric difference



Index([3, 5, 7], dtype='int64')
Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Index([1, 2, 9, 11], dtype='int64')


In [46]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c','d'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [47]:
data['b']

0.5

In [49]:
'a' in data

True

In [50]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [52]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [53]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [54]:
data.array

<NumpyExtensionArray>
[0.25, 0.5, 0.75, 1.0]
Length: 4, dtype: float64

In [55]:
data.to_numpy()

array([0.25, 0.5 , 0.75, 1.  ])

In [64]:
data['e'] = 1.25


In [57]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [59]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [60]:

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [61]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [62]:
# masking
data[(data > 0.3) & (data < 0.8)]


b    0.50
c    0.75
dtype: float64

In [66]:
# fancy indexing
data[['a','e','b']]


a    0.25
e    1.25
b    0.50
dtype: float64

In [68]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [69]:
data[1]


'a'

In [72]:
data[0:1]

1    a
dtype: object

In [75]:
data.loc[1]


'a'

In [77]:
data.loc[1:3]


1    a
3    b
dtype: object

In [3]:
area=pd.Series({'California': 423967, 'Texas': 695662,'New York': 141297, 'Florida': 170312,'Illinois': 149995})
pop=pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [4]:
data['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [5]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [81]:
data.area is data['area']

True

In [82]:
data.pop is data['pop']


False

In [86]:
data["pop"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [87]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [88]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [90]:
newDf=pd.DataFrame(data.T)
newDf


California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [6]:
pop

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [3]:
idx=pd.MultiIndex.from_product([
    ["California","New York","Texas"],
    [2000,2010]],names=["State","Year"])

data=[33871648,37253956,18976457,19378102,20851820,25145561]

pop=pd.Series(data,index=idx)
pop

State       Year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [4]:
pop.unstack()

Year            2000      2010
State                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [5]:
pop.unstack().stack()

State       Year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [6]:
pop.unstack(level=0)

State  California  New York     Texas
Year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [7]:
pop.unstack(level=1)

Year            2000      2010
State                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [8]:
pop_flat = pop.reset_index(name='Population')
pop_flat,type(pop_flat)

(        State  Year  Population
 0  California  2000    33871648
 1  California  2010    37253956
 2    New York  2000    18976457
 3    New York  2010    19378102
 4       Texas  2000    20851820
 5       Texas  2010    25145561,
 pandas.core.frame.DataFrame)

In [9]:
pop_flat.set_index(['State', 'Year'])

Population
State      Year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [10]:
pop_flat["Population"]

0    33871648
1    37253956
2    18976457
3    19378102
4    20851820
5    25145561
Name: Population, dtype: int64

In [11]:
df

calories  duration
0       420        50
1       380        40
2       390        45

In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.random.randint(10, size=(3, 4))
print(A)

[[7 9 0 0]
 [7 9 5 1]
 [5 0 4 1]]


In [7]:
A[0]

array([7, 9, 0, 0], dtype=int32)

In [8]:
A+A[0]

array([[14, 18,  0,  0],
       [14, 18,  5,  1],
       [12,  9,  4,  1]], dtype=int32)

In [18]:
vals1 = np.array([1, np.nan, 3, 4])
print(vals1)

[ 1. nan  3.  4.]


In [19]:
vals1+5

array([ 6., nan,  8.,  9.])

In [20]:
vals1.sum()

np.float64(nan)

In [21]:
np.nansum(vals1)

np.float64(8.0)

In [22]:
np.nanmax(vals1)

np.float64(4.0)

In [23]:
np.nanmin(vals1)

np.float64(1.0)

In [28]:
y=pd.Series([1, np.nan, 2, None])

In [25]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [26]:
x[0] = None

In [27]:
x

0    NaN
1    1.0
dtype: float64

In [29]:
y.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [32]:
y[y.isnull()]

1   NaN
3   NaN
dtype: float64

In [33]:
y[y.notnull()]

0    1.0
2    2.0
dtype: float64

In [34]:
y.dropna()

0    1.0
2    2.0
dtype: float64

In [36]:
y.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
dtype: float64